version: '3.4'

volumes:
  datafiles:

services:
  database:
    image: mysql
    # command: "mysql -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE"
    ports:
      - "3306:3306"
    volumes:
      - "./mysql-scripts:/docker-entrypoint-initdb.d"
    # restart: always
    env_file:
      - ".env"
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  brilliance.api:
    image: ${DOCKER_REGISTRY-}brillianceapi
    ports:
      - "5000:80"
    depends_on: 
      - database
    build:
      context: .
      dockerfile: Brilliance.API/Dockerfile
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development
