version: '3.4'

volumes:
  datafiles:

services:
  database:
    #Pull the latest mysql image
    image: mysql
    #Map port 3306 on the mysql container to port 3306 in the host
    ports:
      - "3306:3306"
    #Specify where the persisted Data should be stored
    volumes:
      - datafiles:/var/lib/mysql
      - "~/sql-scripts/setup.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always
    #Specify Environment Variables for mysql
    environment: 
      MYSQL_ROOT_PASSWORD: Root0++
      MYSQL_USER: newuser
      MYSQL_PASSWORD: pass@word1234
      MYSQL_DATABASE: Usersdb

  brilliance.api:
    image: ${DOCKER_REGISTRY-}brillianceapi
    build:
      context: .
      dockerfile: Brilliance.API/Dockerfile
